### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by klettier** [Zaid-Ajaj/SAFE.React#1]
Hi,

Thanks for you work on this, I just tried to run it and got this issue

![image](https://user-images.githubusercontent.com/3425823/99235915-c544f180-27f6-11eb-9fff-65f547aee807.png)

**Comment by Zaid-Ajaj** [comment]
Hi there @klettier, 
You can run the application without "building first" as shown in the README. `dotnet restore && dotnet run`  in the `server` directory and `npm install && npm start` in the `client` directory. 

The build targets available in the `build` project don't include a "Default" target because there isn't one needed, though I guess I can add a dummy target that doesn't do anything 🤔

**Comment by Zaid-Ajaj** [comment]
Fixed the problem [in this commit](https://github.com/Zaid-Ajaj/SAFE.React/commit/55b9fdff1c7922c07d7eb6005166b4807aaef7f0), now calling `build.cmd` will run the `Pack` target by default which tests both server and client before bundling them into one package. Please give it a try and let me know if anything is working as expected :smile:

**Comment by klettier** [comment]
Running **dotnet run** on server side gives me another issue

![image](https://user-images.githubusercontent.com/3425823/99237589-faeada00-27f8-11eb-83a2-245f32a4c761.png)

**Comment by Zaid-Ajaj** [comment]
You can either adding a global.json file to enforce using `dotnet sdk 3.1` on the solution or simply update to latest version I just fixed which aligns F# core versions across the projects.

**Comment by klettier** [comment]
Thx it works
