### ISSUE TITLE
Error: EMFILE: too many open files, watch

### ISSUE THREAD

**Issue by mastoj** [Zaid-Ajaj/SAFE.React#2]
First of, great work!

I have some problems when starting the app. I've followed the instructions and started the server and client separately, but I get a lot of `Error: EMFILE: too many open files` messages. It looks like it is watch node_modules for some reason. I'm running it on linux, can that impact watch? Is there a way to configure it?

(side comment, it doesn't looks as the gif in the readme but I guess you've made the template "slimmer")

**Comment by Zaid-Ajaj** [comment]
Hi there @mastoj, 

Can you please elaborate on the error, maybe where it is coming from and what machine you are using? I haven't seen that one before 🤔 it works without any problem here on Windows 

> (side comment, it doesn't looks as the gif in the readme but I guess you've made the template "slimmer")

Only the code in the gif looks different (using Elmish) but the usage in both terminal tabs should be the same :smile:

**Comment by mastoj** [comment]
As mentioned, I'm running linux pop os!, that is based of ubuntu. I'm not sure if this is due to your template or because of some issue with the tooling.

I get the error when I run `npm start`, I get the right after it compiled successfully. Based on the example messages below I think it comes from the watch part:

```
Error from chokidar (/home/tomas/tmp/fable3_test/client/node_modules/@pmmmwh/react-refresh-webpack-plugin/client): Error: EMFILE: too many open files, watch '/home/tomas/tmp/fable3_test/client/node_modules/@pmmmwh/react-refresh-webpack-plugin/client'
Error from chokidar (/home/tomas/tmp/fable3_test/client/node_modules/@pmmmwh/react-refresh-webpack-plugin/client/utils): Error: EMFILE: too many open files, watch '/home/tomas/tmp/fable3_test/client/node_modules/@pmmmwh/react-refresh-webpack-plugin/client/utils'
Error from chokidar (/home/tomas/tmp/fable3_test/client/node_modules/@pmmmwh/react-refresh-webpack-plugin/lib/runtime): Error: EMFILE: too many open files, watch '/home/tomas/tmp/fable3_test/client/node_modules/@pmmmwh/react-refresh-webpack-plugin/lib/runtime'
Error from chokidar (/home/tomas/tmp/fable3_test/client/node_modules/@pmmmwh/react-refresh-webpack-plugin/overlay/components): Error: EMFILE: too many open files, watch '/home/tomas/tmp/fable3_test/client/node_modules/@pmmmwh/react-refresh-webpack-plugin/overlay/components'
Error from chokidar (/home/tomas/tmp/fable3_test/client/node_modules/@pmmmwh/react-refresh-webpack-plugin/overlay/containers): Error: EMFILE: too many open files, watch '/home/tomas/tmp/fable3_test/client/node_modules/@pmmmwh/react-refresh-webpack-plugin/overlay/containers'
Error from chokidar (/home/tomas/tmp/fable3_test/client/node_modules/@pmmmwh/react-refresh-webpack-plugin/overlay): Error: EMFILE: too many open files, watch '/home/tomas/tmp/fable3_test/client/node_modules/@pmmmwh/react-refresh-webpack-plugin/overlay'
Error from chokidar (/home/tomas/tmp/fable3_test/client/node_modules/@pmmmwh/react-refresh-webpack-plugin/overlay/utils): Error: EMFILE: too many open files, watch '/home/tomas/tmp/fable3_test/client/node_modules/@pmmmwh/react-refresh-webpack-plugin/overlay/utils'
Error from chokidar (/home/tomas/tmp/fable3_test/client/node_modules/@pmmmwh/react-refresh-webpack-plugin/sockets): Error: EMFILE: too many open files, watch '/home/tomas/tmp/fable3_test/client/node_modules/@pmmmwh/react-refresh-webpack-plugin/sockets'
```

**Comment by Zaid-Ajaj** [comment]
The error seems to come from the [react-refresh-webpack-plugin](https://github.com/pmmmwh/react-refresh-webpack-plugin) the library responsible for React fast-refresh capabilities. The underlying library emitting this error is [chokidar](https://github.com/paulmillr/chokidar) which is nodes generic file watcher. After a search in the issues, it seems that this error is kind of unavoidable unless you do some queuing shenanigans which is what [graceful-fs](https://github.com/isaacs/node-graceful-fs) is attempting to solve. They seem to have a solution for this. 

Since I can't reproduce the errors on my machine, I will ask you to try out these steps:

First of all, you need this library (installed as a development tool)
```bash
cd ./fable3_test/client
npm install --save-dev graceful-fs
```
Then inside your `webpack.config.js` file (and later if this works also in `webpack.tests.js`) apply the [global patching](https://github.com/isaacs/node-graceful-fs#global-patching) of `graceful-fs`:
```js
// webpack.config.js
var realFs = require('fs')
var gracefulFs = require('graceful-fs')
gracefulFs.gracefulify(realFs)

// rest of the file, unchanged...
```
I can confirm that applying this patch at least doesn't break my webpack config so that's a good start :smile: 

Please give it a try and let me know how it goes :pray:

**Comment by mastoj** [comment]
It worked, I can create a PR on it later today.

**Comment by Zaid-Ajaj** [comment]
Done, should be available in latest :smile:

**Comment by mastoj** [comment]
Cool!
