### ISSUE TITLE
SCSS integration doesn't work 

### ISSUE THREAD

**Issue by landy** [Zaid-Ajaj/SAFE.React#3]
Hello Zaid, I've tried this template and encountered a strange behaviour.

when you add a new div with some random class like 

```
Html.h1 [
    prop.className "foo"
    prop.text count
]
```

and then in the main.scss 
```
.foo {
  background-color: black;
}
```

the styles are no applied to the elements in the browser. But styling for body works. So I guess it is somehow connected to react fast refresh or something. 

the style is written like this in the head part of the webpage 

```
._1IMXHl1_d5q7_2L3Ic6UCR {
  background-color: black;
}
```

**Comment by Zaid-Ajaj** [comment]
Hi there @landy, I believe this behaviour is caused by the fact that the CSS is now has enabled _modules_ by default which means you can't use global classes for styling directly, you can read all about it [here](https://webpack.js.org/loaders/css-loader/#modules) but is it rather simple:

The idea behind scoped CSS modules is that you don't use global classes for you app because those could collide with different elements across the application. If you still want a global class, you should specify that it is global like this:
```css
:global(.foo) {
  background-color: black;
}
```

And to use locally scoped modules properly:
```fs
// load the style sheet
let stylesheet = Stylesheet.load "./styles/component.css"
// access generated class names
let foo : string = stylesheet.["foo"]
```
Example with Feliz:
```fs
let stylesheet = Stylesheet.load "./styles/component.css"

Html.h1 [
    prop.className stylesheet.["foo"]
    prop.text count
]
```

### Disabling Scoped Modules
Go to `webpack.config.js` and make `modules: false` in here:
```js
                test: /\.(sass|scss|css)$/,
                use: [
                    isProduction
                        ? MiniCssExtractPlugin.loader
                        : 'style-loader',
                    {
                        loader: 'css-loader',
                        options: {
                            modules: true
                        }
                    },
                    {
                        loader: 'sass-loader',
                        options: { implementation: require("sass") }
                    }
                ],
            },
```

**Comment by landy** [comment]
wow! just wow! thank you for very VERY detailed explanation of the problem.

**Comment by Zaid-Ajaj** [comment]
No problem @landy, I also just added docs to the README on how to use scoped CSS modules, let me know if I missed anything :wink:
